### PR TITLE
Some preview related changes

### PR DESCRIPTION
**Pull request by bell07**
moved textures folder reading to the bottom to be sure all functions are available. 
Use the multiskin.add_preview to collect previews instead of direct filling skin_previews
add support for previews in multiskin/textures. Bevore it was only available for 3rd-party mods
changed the preview behaviour. Store per skin preview. The API is changed also for multiskin.add_preview()

### CODE REVIEW

**Comment by stujones11** [comment]
Sorry but this seems like a lot of change to store the preview texture name when it can be easily constructed from the skin name. This table could theoretically become quite large if a server were to have several thousands of skins. I do agree, however, to the local directory preview search, multiskin may as well support previews too.

**Comment by bell07** [comment]
I think ahead to support other skins provider like [character_creator](https://github.com/minetest-mods/character_creator). Currently the creator does not have any previews, but if implemented it will be something composed not the *_preview.png.
in my skinsdb fork I collect the previews as proposed [skinlist.lua](https://github.com/bell07/minetest-skinsdb/blob/master/skinlist.lua) and there is no issues with > 1000 skins.
I do not see the difference in size between the curently implemented `skin_previews[skin] = true` and my proposed `skin_previews[skin] = preview`. The entry count is the same. Ok, you loose some bytes to store the preview texture strings but you save the string calcualtions `skin:gsub(".png$", "_preview.png")` at the other side.

By the way, as I requested for skins metadata, maybe it will be beter to merge both requirements into one since the preview texture string is abstact just a metadata too. So my new proposal is to start a new table like
`skin_metadata[skin] = { preview = "xy_preview.png", author = "XYZ", .....}`
and new methods like `multiskin.get_metadata(skin, "preview")` / `multiskin.set_metadata(skin, "preview", "xy_preview.png")`. The existing methods `multiskin.get_preview()` / `multiskin.add_preview()` could be still wrappers for compatibility

**Comment by stujones11** [comment]
The latter option sounds reasonable I guess and there is no need to worry over compatibility as the mod is still WIP. I do have some other api changes planned for before release, like adding boilerplate to avoid exposing the local tables to the global namespace.

**Comment by bell07** [comment]
Ok, I think we can close this PR and continue the discussion in the "metadata" issue. Basically I think multiskin needs to provide all additional data for skins because of MT-security implementation. If I need the preview files or metadata-files content from other mods the security does not allow to read them.

**Comment by stujones11** [comment]
Yes, mod security is an issue, however, this mod already has insecure features that can only be enabled by adding multiskin to trusted mods so this would also be the case for metadata from other skin mods.

**Pull request closed without merging**
